package Lab9;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

public class LabHilos extends javax.swing.JFrame {

    public LabHilos() {
        initComponents();
        mostrar = new Fecha_Hora(jl_horaactual, jl_fecha);
        Thread hiloDate = new Thread(mostrar);
        hiloDate.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_fondo = new javax.swing.JPanel();
        panel_bienvenido = new javax.swing.JPanel();
        jl_bienvenido = new javax.swing.JLabel();
        jl_fechahoy = new javax.swing.JLabel();
        jl_hora = new javax.swing.JLabel();
        jl_fecha = new javax.swing.JLabel();
        jl_horaactual = new javax.swing.JLabel();
        jl_compu = new javax.swing.JLabel();
        jl_empresa = new javax.swing.JLabel();
        jb_subir = new javax.swing.JButton();
        jl_subiendo = new javax.swing.JLabel();
        jp_barra = new javax.swing.JProgressBar();
        lj_archivo = new javax.swing.JLabel();
        area = new javax.swing.JScrollPane();
        jt_area = new javax.swing.JTextArea();
        jb_agregar = new javax.swing.JButton();
        jl_logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_fondo.setBackground(new java.awt.Color(255, 204, 204));

        panel_bienvenido.setBackground(new java.awt.Color(255, 153, 153));

        jl_bienvenido.setFont(new java.awt.Font("Wide Latin", 3, 14)); // NOI18N
        jl_bienvenido.setText("B I E N V E N I D O");

        jl_fechahoy.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jl_fechahoy.setText("Fecha de Hoy:");

        jl_hora.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jl_hora.setText("Hora Actual:");

        jl_fecha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jl_fecha.setForeground(new java.awt.Color(255, 255, 255));
        jl_fecha.setText("00/00/0000");

        jl_horaactual.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jl_horaactual.setForeground(new java.awt.Color(255, 255, 255));
        jl_horaactual.setText("00:00:00");

        jl_compu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/compu.png"))); // NOI18N

        javax.swing.GroupLayout panel_bienvenidoLayout = new javax.swing.GroupLayout(panel_bienvenido);
        panel_bienvenido.setLayout(panel_bienvenidoLayout);
        panel_bienvenidoLayout.setHorizontalGroup(
            panel_bienvenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_bienvenidoLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(panel_bienvenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_horaactual)
                    .addComponent(jl_fecha)
                    .addComponent(jl_bienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_fechahoy)
                    .addComponent(jl_hora))
                .addContainerGap())
            .addGroup(panel_bienvenidoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jl_compu, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_bienvenidoLayout.setVerticalGroup(
            panel_bienvenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bienvenidoLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jl_bienvenido)
                .addGap(32, 32, 32)
                .addComponent(jl_fechahoy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl_fecha)
                .addGap(39, 39, 39)
                .addComponent(jl_hora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl_horaactual)
                .addGap(18, 18, 18)
                .addComponent(jl_compu, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jl_empresa.setFont(new java.awt.Font("HP Simplified", 3, 36)); // NOI18N
        jl_empresa.setForeground(new java.awt.Color(0, 102, 102));
        jl_empresa.setText("BOROA CLUD");

        jb_subir.setBackground(new java.awt.Color(255, 102, 102));
        jb_subir.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jb_subir.setForeground(new java.awt.Color(255, 255, 255));
        jb_subir.setText("Subir Archivo");
        jb_subir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_subirActionPerformed(evt);
            }
        });

        jl_subiendo.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jl_subiendo.setText("Subiendo Archivo:");

        lj_archivo.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lj_archivo.setText("Archivo:");

        jt_area.setBackground(new java.awt.Color(255, 153, 153));
        jt_area.setColumns(20);
        jt_area.setForeground(new java.awt.Color(255, 255, 255));
        jt_area.setRows(5);
        area.setViewportView(jt_area);

        jb_agregar.setBackground(new java.awt.Color(255, 102, 102));
        jb_agregar.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jb_agregar.setForeground(new java.awt.Color(255, 255, 255));
        jb_agregar.setText("Guardar & Modificar");
        jb_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_agregarActionPerformed(evt);
            }
        });

        jl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/download-removebg-preview (11).png"))); // NOI18N

        javax.swing.GroupLayout panel_fondoLayout = new javax.swing.GroupLayout(panel_fondo);
        panel_fondo.setLayout(panel_fondoLayout);
        panel_fondoLayout.setHorizontalGroup(
            panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fondoLayout.createSequentialGroup()
                .addComponent(panel_bienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fondoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lj_archivo)
                        .addGap(215, 215, 215))
                    .addGroup(panel_fondoLayout.createSequentialGroup()
                        .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_fondoLayout.createSequentialGroup()
                                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_fondoLayout.createSequentialGroup()
                                        .addGap(142, 142, 142)
                                        .addComponent(jl_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel_fondoLayout.createSequentialGroup()
                                        .addGap(204, 204, 204)
                                        .addComponent(jb_subir))
                                    .addGroup(panel_fondoLayout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(jl_subiendo)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jl_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panel_fondoLayout.createSequentialGroup()
                                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_fondoLayout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(jp_barra, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel_fondoLayout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel_fondoLayout.createSequentialGroup()
                                        .addGap(189, 189, 189)
                                        .addComponent(jb_agregar)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        panel_fondoLayout.setVerticalGroup(
            panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_bienvenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_fondoLayout.createSequentialGroup()
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_fondoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jl_empresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_subir)
                        .addGap(18, 18, 18)
                        .addComponent(jl_subiendo))
                    .addGroup(panel_fondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jl_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_barra, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lj_archivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_agregar)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_subirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_subirActionPerformed
        JFileChooser seleccionar = new JFileChooser("./");
        FileNameExtensionFilter permitidos = new FileNameExtensionFilter("Archivos.txt", "txt");
        seleccionar.setFileFilter(permitidos);
        int seleccionado = seleccionar.showOpenDialog(this);

        if (seleccionado == JFileChooser.APPROVE_OPTION) {
            dato = seleccionar.getSelectedFile();
            jt_area.setText("");

            jp_barra.setValue(100);

            corre = new Barra(jp_barra, jt_area, dato);
            Thread bcorre = new Thread(corre);
            bcorre.start();
        }

    }//GEN-LAST:event_jb_subirActionPerformed

    private void jb_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agregarActionPerformed
        try {
            FileWriter fw = new FileWriter(dato, false);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(jt_area.getText());
            bw.flush();
            bw.close();
            fw.close();
            JOptionPane.showMessageDialog(this, "Se ha modificado el archivo con exito.");
        } catch (IOException ex) {
            Logger.getLogger(LabHilos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jb_agregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LabHilos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LabHilos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LabHilos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LabHilos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LabHilos().setVisible(true);
            }
        });
    }

    Fecha_Hora mostrar;
    File dato;
    Barra corre;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane area;
    private javax.swing.JButton jb_agregar;
    private javax.swing.JButton jb_subir;
    private javax.swing.JLabel jl_bienvenido;
    private javax.swing.JLabel jl_compu;
    private javax.swing.JLabel jl_empresa;
    private javax.swing.JLabel jl_fecha;
    private javax.swing.JLabel jl_fechahoy;
    private javax.swing.JLabel jl_hora;
    private javax.swing.JLabel jl_horaactual;
    private javax.swing.JLabel jl_logo;
    private javax.swing.JLabel jl_subiendo;
    private javax.swing.JProgressBar jp_barra;
    private javax.swing.JTextArea jt_area;
    private javax.swing.JLabel lj_archivo;
    private javax.swing.JPanel panel_bienvenido;
    private javax.swing.JPanel panel_fondo;
    // End of variables declaration//GEN-END:variables
}
